sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJjitWWU3f4JFtvZ5an
    access-key-secret: DJav8VZvnYgW1qdVr5AONmQTtqcxUW
    bucket-name: big-event-ali
    #access-key-id: LTAI5tJjitWWU3f4JFtvZ5an
    #access-key-secret: DJav8VZvnYgW1qdVr5AONmQTtqcxUW
    #bucket-name: big-event-ali
  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 10
  wechat:
    appid: wxcfadd6e5a7b9f3e6
    secret: 8f1595af7a2508bd4cfc9564e84b46cc
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
